"""
migrations/env.py
------------------
Alembic environment for Turtle's cloud (Neon) Postgres schema (ledger 3.1).

DATABASE_URL_DIRECT, not DATABASE_URL: DATABASE_URL is documented in
.env.example as Neon's *pooled* endpoint (PgBouncer, transaction mode) —
correct for the app's own short-lived serverless queries, but wrong for DDL.
Per the Postgres docs, transaction-mode pooling does not support session-level
features, and CREATE INDEX CONCURRENTLY cannot run inside a transaction block
at all (pgbouncer's transaction mode wraps every statement in one). Alembic
must therefore run against Neon's direct, non-pooler host.

Fails loudly and early when DATABASE_URL_DIRECT is unset — this module never
falls back to DATABASE_URL. A silent fallback would route DDL over the
pooler, silently reintroducing the exact failure mode this design avoids
(works today, breaks the day a migration finally needs CONCURRENTLY or a
session-level setting).

This module deliberately does not import anything from the `core` package:
it has no dependency on app settings/config, so `alembic upgrade head` can run
from a minimal environment (this repo's CI/deploy jobs, or an operator's own
shell) with only alembic/sqlalchemy/psycopg installed.
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Raw-SQL migrations only (ledger 3.1: "0001_baseline copies today's DDL
# strings verbatim" — not autogenerated from ORM metadata), so there is no
# SQLAlchemy metadata object for autogenerate to diff against.
target_metadata = None


def get_url() -> str:
    """Return the direct (non-pooler) Neon connection string, translated to
    SQLAlchemy's psycopg3 dialect. Raises immediately, naming the variable,
    if DATABASE_URL_DIRECT is not set — see module docstring for why this
    must never fall back to DATABASE_URL.
    """
    raw = os.environ.get("DATABASE_URL_DIRECT", "").strip()
    if not raw:
        raise RuntimeError(
            "DATABASE_URL_DIRECT is not set. Alembic DDL must run against "
            "Neon's DIRECT (non-pooler) connection string — see .env.example. "
            "Refusing to fall back to DATABASE_URL (the pooled endpoint): "
            "transaction-mode pooling doesn't support session features and "
            "cannot run CREATE INDEX CONCURRENTLY inside its wrapping "
            "transaction. Set DATABASE_URL_DIRECT and re-run."
        )
    # SQLAlchemy's plain "postgresql://" scheme resolves to psycopg2, which
    # this project does not install (it uses psycopg 3 — requirements.txt's
    # "psycopg[binary,pool]>=3.2"). Force the psycopg3 dialect explicitly
    # rather than relying on whichever driver happens to be importable.
    if raw.startswith("postgresql+"):
        return raw
    if raw.startswith("postgresql://"):
        return "postgresql+psycopg://" + raw[len("postgresql://"):]
    if raw.startswith("postgres://"):
        return "postgresql+psycopg://" + raw[len("postgres://"):]
    return raw


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection (`alembic upgrade
    head --sql`). Still requires DATABASE_URL_DIRECT to be set (get_url()
    raises otherwise) so the emitted SQL's dialect assumptions match what
    the direct host actually is.
    """
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
