"""baseline: today's cloud schema, copied verbatim from core/storage/cloud/

Revision ID: 0001
Revises:
Create Date: 2026-09-26

Ledger 3.1 (review/2026-09-25-decision-ledger.md, Phase 3 row 3.1):

    "0001_baseline copies today's DDL strings verbatim, checked against a
    pg_dump --schema-only of production; production is `alembic stamp 0001`
    once (owner)."

This revision is NOT autogenerated (`alembic revision --autogenerate` would
normalise and reorder statements and could silently lose details that matter,
e.g. a partial index's WHERE clause). Every statement below is copied
character-for-character from the `_CREATE_TABLE_SQL` / `_CREATE_TABLES_SQL` /
`_CREATE_INDEX_SQL` constants in core/storage/cloud/*.py as they read on the
commit this revision was written against (b7f601b). One exception, called out
inline: PgVectorStore/PgChunkVectorStore's `%(dim)s` template placeholder is
already substituted (dim=1024) the same way core/storage/cloud/pgvector_store.py
substitutes it at import time — the *substituted* string is what actually runs
in production, so that is what belongs here.

`test/cloud_integration/migrations_schema_parity_test.py` is the control that
these 18 `CREATE TABLE` statements (17 from core/tenant_purge.py's
_TABLE_USER_COLUMNS plus purge_log, deliberately excluded from purging) stay
byte-for-byte load-bearing-equivalent to the stores: it builds one schema by
importing and executing the stores' own DDL constants directly, a second by
running this migration, and asserts `information_schema`/`pg_indexes` report
the same tables, columns, indexes (including partial-index WHERE clauses) and
primary keys in both.

`link_codes.expected_email`: core/storage/cloud/account_linking_store.py adds
this column via a separate idempotent `ALTER TABLE ... ADD COLUMN IF NOT
EXISTS` for tables created before the column existed, but its own
`CREATE TABLE` statement already declares the column inline (it was folded in
before this migration was written) — so it is copied here as part of the one
`CREATE TABLE`, and the ALTER is not replayed.

`CREATE EXTENSION IF NOT EXISTS vector`: lives in the pool's per-connection
init callback (core/storage/cloud/__init__.py's get_pg_pool), not in any
store's own DDL block — the ledger's 3.2 row describes it as coming "from the
stores", which is imprecise about the exact location, but the statement text
is unaffected and is reproduced here so the baseline can build vector_docs/
vector_chunks from an empty database with no other bootstrap step.

Downgrade: implemented (drops all 18 tables in an order safe against any
future FK addition, and does NOT drop the `vector` extension — see
downgrade()'s docstring for why). `alembic downgrade base` was verified
locally against this revision only in code review, not against a live
Postgres (this sandbox has no local Postgres); the schema-parity test above
runs `alembic upgrade head` against a real Postgres in CI, not the downgrade
path.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Verbatim DDL, one block per core/storage/cloud/*.py module, in the same
# order `grep -n "CREATE TABLE" core/storage/cloud/*.py` lists them.
# ---------------------------------------------------------------------------

# core/storage/cloud/__init__.py::get_pg_pool's per-connection init callback.
_CREATE_EXTENSION_SQL = "CREATE EXTENSION IF NOT EXISTS vector"

# core/storage/cloud/account_linking_store.py::_CREATE_TABLE_SQL
_LINK_CODES_SQL = """
CREATE TABLE IF NOT EXISTS link_codes (
    code TEXT PRIMARY KEY,
    channel TEXT NOT NULL,
    channel_user_id TEXT NOT NULL,
    source_user_id TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    reserved_for TEXT,
    reserved_at TIMESTAMPTZ,
    expected_email TEXT
)
"""

# core/storage/cloud/calendar_token_store.py::_CREATE_TABLE_SQL
_CALENDAR_TOKENS_SQL = """
CREATE TABLE IF NOT EXISTS calendar_tokens (
    user_id TEXT PRIMARY KEY,
    token_json TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# core/storage/cloud/confirmation_state_store.py::_CREATE_TABLE_SQL
_CONFIRMATION_STATE_SQL = """
CREATE TABLE IF NOT EXISTS confirmation_state (
    user_id TEXT PRIMARY KEY,
    pending JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# core/storage/cloud/identity_store.py::_CREATE_TABLES_SQL (4 tables + 1 index)
_USERS_SQL = """
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    primary_email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_CHANNEL_MAPPINGS_SQL = """
CREATE TABLE IF NOT EXISTS channel_mappings (
    channel TEXT NOT NULL,
    channel_user_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    PRIMARY KEY (channel, channel_user_id)
)
"""
_CLAIMED_TOKENS_SQL = """
CREATE TABLE IF NOT EXISTS claimed_tokens (
    jti TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_ACCOUNT_MARKERS_SQL = """
CREATE TABLE IF NOT EXISTS account_markers (
    user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL,
    channel TEXT NOT NULL
)
"""
_IDX_ACCOUNT_MARKERS_EMAIL_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_account_markers_email ON account_markers(email)"
)

# core/storage/cloud/journal_store.py
_JOURNAL_EVENTS_SQL = """
CREATE TABLE IF NOT EXISTS journal_events (
    user_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    payload JSONB NOT NULL,
    PRIMARY KEY (user_id, event_id)
)
"""
_IDX_JOURNAL_EVENTS_USER_OBSERVED_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_journal_events_user_observed "
    "ON journal_events(user_id, observed_at)"
)

# core/storage/cloud/personal_memory_store.py::_CREATE_TABLES_SQL (2 tables)
_PERSONAL_MEMORY_TOPICS_SQL = """
CREATE TABLE IF NOT EXISTS personal_memory_topics (
    user_id TEXT NOT NULL,
    topic_name TEXT NOT NULL,
    content TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, topic_name)
)
"""
_PERSONAL_MEMORY_DAILY_LOGS_SQL = """
CREATE TABLE IF NOT EXISTS personal_memory_daily_logs (
    user_id TEXT NOT NULL,
    log_date TEXT NOT NULL,
    content TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, log_date)
)
"""

# core/storage/cloud/pgvector_store.py. _VECTOR_DIM = 1024 is substituted into
# the store's own `%(dim)s` template at import time; reproduced here already
# substituted, matching what actually runs.
_VECTOR_DOCS_SQL = """
CREATE TABLE IF NOT EXISTS vector_docs (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    doc_id TEXT NOT NULL,
    text TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding vector(1024) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_IDX_VECTOR_DOCS_USER_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_vector_docs_user ON vector_docs(user_id) "
    "WHERE NOT deleted"
)
_VECTOR_CHUNKS_SQL = """
CREATE TABLE IF NOT EXISTS vector_chunks (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    chunk_id TEXT,
    session_id TEXT NOT NULL DEFAULT 'unknown',
    content TEXT NOT NULL DEFAULT '',
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding vector(1024) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_IDX_VECTOR_CHUNKS_USER_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_vector_chunks_user ON vector_chunks(user_id) "
    "WHERE NOT deleted"
)

# core/storage/cloud/postgres_store.py
_SESSIONS_SQL = """
CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    data JSONB NOT NULL,
    user_id TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_IDX_SESSIONS_USER_SQL = "CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)"

# core/storage/cloud/purge_log_store.py
_PURGE_LOG_SQL = """
CREATE TABLE IF NOT EXISTS purge_log (
    id BIGSERIAL PRIMARY KEY,
    user_id_sha256 TEXT NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    counts JSONB NOT NULL
)
"""
_IDX_PURGE_LOG_USER_ID_SHA256_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_purge_log_user_id_sha256 "
    "ON purge_log(user_id_sha256)"
)

# core/storage/cloud/rag_session_staging_store.py
_RAG_SESSION_STAGING_SQL = """
CREATE TABLE IF NOT EXISTS rag_session_staging (
    user_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    creation_time TEXT NOT NULL,
    conversations JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# core/storage/cloud/routine_last_fired_store.py
_ROUTINE_LAST_FIRED_SQL = """
CREATE TABLE IF NOT EXISTS routine_last_fired (
    user_id TEXT NOT NULL,
    routine_key TEXT NOT NULL,
    fire_bucket TEXT NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, routine_key, fire_bucket)
)
"""
_IDX_ROUTINE_LAST_FIRED_CLAIMED_AT_SQL = (
    "CREATE INDEX IF NOT EXISTS idx_routine_last_fired_claimed_at "
    "ON routine_last_fired(claimed_at)"
)

# core/storage/cloud/routine_outbox_store.py
_ROUTINE_OUTBOX_SQL = """
CREATE TABLE IF NOT EXISTS routine_outbox (
    user_id TEXT PRIMARY KEY,
    frames JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# core/storage/cloud/telemetry_claim_store.py
_TELEMETRY_ONCE_SQL = """
CREATE TABLE IF NOT EXISTS telemetry_once (
    user_id TEXT NOT NULL,
    event TEXT NOT NULL,
    first_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, event)
)
"""


def upgrade() -> None:
    op.execute(_CREATE_EXTENSION_SQL)

    op.execute(_LINK_CODES_SQL)
    op.execute(_CALENDAR_TOKENS_SQL)
    op.execute(_CONFIRMATION_STATE_SQL)

    op.execute(_USERS_SQL)
    op.execute(_CHANNEL_MAPPINGS_SQL)
    op.execute(_CLAIMED_TOKENS_SQL)
    op.execute(_ACCOUNT_MARKERS_SQL)
    op.execute(_IDX_ACCOUNT_MARKERS_EMAIL_SQL)

    op.execute(_JOURNAL_EVENTS_SQL)
    op.execute(_IDX_JOURNAL_EVENTS_USER_OBSERVED_SQL)

    op.execute(_PERSONAL_MEMORY_TOPICS_SQL)
    op.execute(_PERSONAL_MEMORY_DAILY_LOGS_SQL)

    op.execute(_VECTOR_DOCS_SQL)
    op.execute(_IDX_VECTOR_DOCS_USER_SQL)
    op.execute(_VECTOR_CHUNKS_SQL)
    op.execute(_IDX_VECTOR_CHUNKS_USER_SQL)

    op.execute(_SESSIONS_SQL)
    op.execute(_IDX_SESSIONS_USER_SQL)

    op.execute(_PURGE_LOG_SQL)
    op.execute(_IDX_PURGE_LOG_USER_ID_SHA256_SQL)

    op.execute(_RAG_SESSION_STAGING_SQL)

    op.execute(_ROUTINE_LAST_FIRED_SQL)
    op.execute(_IDX_ROUTINE_LAST_FIRED_CLAIMED_AT_SQL)

    op.execute(_ROUTINE_OUTBOX_SQL)

    op.execute(_TELEMETRY_ONCE_SQL)


def downgrade() -> None:
    """Drop every table this revision created.

    Does NOT `DROP EXTENSION vector`: extensions are database-wide, not
    owned by this migration's tables, and dropping it here could break any
    other schema/object in the same database that also depends on the
    `vector` type. Leaving it installed is harmless (CREATE EXTENSION IF NOT
    EXISTS is idempotent, and an installed-but-unused extension costs
    nothing at rest) whereas dropping it is a decision with a blast radius
    wider than "undo revision 0001" implies.

    No FKs exist between these tables today, so drop order does not matter
    for correctness; the reverse-of-creation order below is kept anyway so a
    future revision that adds a foreign key between two of these tables
    doesn't have to also remember to update this function.
    """
    op.execute("DROP TABLE IF EXISTS telemetry_once")
    op.execute("DROP TABLE IF EXISTS routine_outbox")
    op.execute("DROP TABLE IF EXISTS routine_last_fired")
    op.execute("DROP TABLE IF EXISTS rag_session_staging")
    op.execute("DROP TABLE IF EXISTS purge_log")
    op.execute("DROP TABLE IF EXISTS sessions")
    op.execute("DROP TABLE IF EXISTS vector_chunks")
    op.execute("DROP TABLE IF EXISTS vector_docs")
    op.execute("DROP TABLE IF EXISTS personal_memory_daily_logs")
    op.execute("DROP TABLE IF EXISTS personal_memory_topics")
    op.execute("DROP TABLE IF EXISTS journal_events")
    op.execute("DROP TABLE IF EXISTS account_markers")
    op.execute("DROP TABLE IF EXISTS claimed_tokens")
    op.execute("DROP TABLE IF EXISTS channel_mappings")
    op.execute("DROP TABLE IF EXISTS users")
    op.execute("DROP TABLE IF EXISTS confirmation_state")
    op.execute("DROP TABLE IF EXISTS calendar_tokens")
    op.execute("DROP TABLE IF EXISTS link_codes")
